# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exprgrep < Formula
  desc "Filter JSONL lines by an expr expression"
  homepage "https://github.com/jtarchie/exprgrep"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.1/exprgrep_0.1.1_darwin_amd64.tar.gz"
      sha256 "ac51efb1d26750b3b02730b7ca3385845412e47535a99097f2dfac31258b0b3c"

      define_method(:install) do
        bin.install "exprgrep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.1/exprgrep_0.1.1_darwin_arm64.tar.gz"
      sha256 "67ff3b157c3330bd15d6ae10b4fb0a1a1d604a70ddad71aaa2d08f4c5424066f"

      define_method(:install) do
        bin.install "exprgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.1/exprgrep_0.1.1_linux_amd64.tar.gz"
      sha256 "b9e2efe2f74225b8b577bc2200264deb932e374cb7d4c17e9941262e41534a7b"
      define_method(:install) do
        bin.install "exprgrep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.1/exprgrep_0.1.1_linux_arm64.tar.gz"
      sha256 "4297078864b94618147704cd0ec6e3ce707f1ef1d31faf472e3aef7041591ed5"
      define_method(:install) do
        bin.install "exprgrep"
      end
    end
  end

  test do
    system "#{bin}/exprgrep", "--help"
  end
end
