# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exprgrep < Formula
  desc "Filter JSONL lines by an expr expression"
  homepage "https://github.com/jtarchie/exprgrep"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.0/exprgrep_0.1.0_darwin_amd64.tar.gz"
      sha256 "1095030cc1dff585cb25990390ee94122684f694d1ef5e9d2e4ab1dd8b509028"

      define_method(:install) do
        bin.install "exprgrep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.0/exprgrep_0.1.0_darwin_arm64.tar.gz"
      sha256 "f2a09ce3bc7a95a12f090b1cac60d4f346b6a519eb29cde7c28f64af133afc4e"

      define_method(:install) do
        bin.install "exprgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.0/exprgrep_0.1.0_linux_amd64.tar.gz"
      sha256 "52feab1228281c9afcf5a97360d1a9503f3ead0799bc5c2c1f5c11a177b9aa98"
      define_method(:install) do
        bin.install "exprgrep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.0/exprgrep_0.1.0_linux_arm64.tar.gz"
      sha256 "106fb0eabd999d8eac36c5677ff47b2c8840c4e56fa9c57a3b8fbf4e89f65dd2"
      define_method(:install) do
        bin.install "exprgrep"
      end
    end
  end

  test do
    system "#{bin}/exprgrep", "--help"
  end
end
