# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exprgrep < Formula
  desc "Filter JSONL lines by an expr expression"
  homepage "https://github.com/jtarchie/exprgrep"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.2/exprgrep_0.1.2_darwin_amd64.tar.gz"
      sha256 "f37c66fb69822eecb9dcfa2ab435eb0c7a2561ebdf49fdf3824e3f062b6d3d50"

      define_method(:install) do
        bin.install "exprgrep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.2/exprgrep_0.1.2_darwin_arm64.tar.gz"
      sha256 "1190de94b7add9163f2edb860353642c0828f6b34eabf81d11fad318c73c32fc"

      define_method(:install) do
        bin.install "exprgrep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.2/exprgrep_0.1.2_linux_amd64.tar.gz"
      sha256 "09c74cd95954a7df24783c8872e60314cb8006692660fcaf13496c684a2796de"
      define_method(:install) do
        bin.install "exprgrep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jtarchie/exprgrep/releases/download/v0.1.2/exprgrep_0.1.2_linux_arm64.tar.gz"
      sha256 "18c6d5c2e4532c360a679e5e140a71a95cb8738abf3f9bdce7f51c826b3d1747"
      define_method(:install) do
        bin.install "exprgrep"
      end
    end
  end

  test do
    system "#{bin}/exprgrep", "--help"
  end
end
